# Example config file to use as a starting point.
# Please visit https://docs.beetleboxci.com/docs/config/configuration-yaml for guidance on setting up your configuration file.

# Define a runner that will be used to run a job
runners:
 ubuntu-runner:
  image: public.ecr.aws/y2s4f3y9/ubuntu-generic

# Define a job to be performed during a workflow
jobs:   
 run-sim-job:
  # Specify the runner used to perform this job
  runner: ubuntu-runner
  output: 
   artifact: 
    - ci_for_fpgas.sim/
  volumes:
    - mount:
        name: volume1
        path: /tools/Xilinx

  # Define one or more steps to execute commands as part of the job
  steps:
   - run:
      name: Initalise vivado environment
      command: |
        apt-get update
        apt-get install locales
        locale
        locale-gen "en_US.UTF-8"
        update-locale LANG=en_US.UTF-8
   - run:
      name: Run Simulation
      command: |
        cd /tools/Xilinx/Vivado/2023.1/
        source settings64.sh
        cd $HOME
        ls
        vivado -mode batch -source tcl_scripts/run_sim.tcl  | tee simulation_output.txt
   - run:
      name: Parse simulation for errors
      command: | 
        # Path to the file to be checked
        FILE_PATH="./simulation_output.txt"
        # Check if the file exists
        if [[ ! -f "$FILE_PATH" ]]; then
         echo "File does not exist: $FILE_PATH"
          exit 1
        fi
        # Search for the phrase "Error: Assertion violation" in the file
        if grep -q "Error: Assertion violation" "$FILE_PATH"; then
          echo "Error: Assertion violation found in file."
          exit 1
        else
          echo "No assertion violations found. Passing."
          exit 0
        fi
   - run:
      name: Run Bitstream Generation
      command: |
        cd /tools/Xilinx/Vivado/2023.1/
        source settings64.sh
        cd $HOME
        ls
        vivado -mode batch -source tcl_scripts/run_gen_bitstream.tcl  | tee bit_stream_gen_output.txt

# Define a workflow to orchestrate a job
workflows:
 run-sim-workflow:
  jobs:
   - run-sim-job
